Initilisation du projet Quarkus avec endpoint /hello #5
adriens/api-forfaits-opt pull request #15
Opened 2024-12-10 00:10 UTC by morgancarre

Fixes - #5

- Initialisation d'un projet Quarkus avec Java 23, Maven 3.9.9, Quarkus 3.17.3.
- Endpoint `/hello`.

2024-12-10 07:21 UTC, adriens requested changes
le pom.xml et tout le reste du projet doit être  à la racine de la repo

2024-12-10 10:09 UTC, morgancarre commented
Je crois que c'est bon

2024-12-10 21:42 UTC, adriens commented
Dans le README il manque les instructtions pour compiler/démarrer....genre via une section dédiée :thinking:

2024-12-11 23:18 UTC, adriens requested changes
Il ne faut pas utiliser `mvnw`, mais uniquement `mvn` : peuxtu stp updater la doc et virer tout ce qui est en lien avec `mvnw` ?

2024-12-12 21:52 UTC, morgancarre commented
@adriens c'est bon pour les commandes ?

2024-12-13 03:33 UTC, adriens commented
Il faut faire le ménage
![image](https://github.com/user-attachments/assets/e0e95168-2394-45c2-992d-f0916c337f74)

2024-12-15 22:34 UTC, morgancarre commented
@adriens j'ai supprimer aussi le repertoire .mvn , c'est good ?

2024-12-16 01:33 UTC, adriens commented
As tu mis ce répertoire dans ton .gitignore ?

2024-12-16 02:02 UTC, morgancarre commented
Il faut plutôt le mettre dans le .gitignore ? Parce que j'ai regardé à l'intérieur et il n'y avait que des fichiers en rapport avec Maven Wrapper, donc je l'ai simplement supprimé.

2024-12-16 21:48 UTC, adriens commented
Il faudra faire une PR pour pousser le rapport

2024-12-16 21:48 UTC, merged