Dockerfile pour conteneuriser #8 Instructions dans README pour compiler rapport #19
adriens/api-forfaits-opt pull request #20
Opened 2024-12-26 02:50 UTC by morgancarre

fixes
- #8 
- #19

2024-12-26 22:56 UTC, adriens requested changes
## Section _Lancer le conteneur_

- Eliminer le screenshot de l'appel `httpie` au profit d'une ligne de commande `http`
- Eliminer `/hello` et taper sur les forfaits de l'API `/api/forfaits`
- Eliminer les commenataires superflus _se rentre dans le repertoire rapport/ du dépôt__
- Eliminer le screenshot _Lire le rapport_ au profit de `xdg-open rapport_de_stage.pdf`
- Généralement on fait court pour les noms de répertoires : rapport -> `doc`
- typo : "nitialiser " -> "initialiser"
- :clap: le rapport est déja très beau!
- les noms de table doivent **toujours être en minuscules** et **pluriel** : `forfaits` au lieu de `Forfaits`
- Colorer le code java (https://tex.stackexchange.com/questions/352674/colorize-the-source-code)
- il manque le ToC dans le rapport : il faut le générer avec `\tableofcontents`
- Renommeer _ Outils et technologies utilisés_ en _Stack_ et ajouter Ubuntu
- Ajouter une section bibliographie avec quelques liens vers des articles connexes ou en lien avec le sujet
- Ajouter une section remerciements

2024-12-27 03:26 UTC, morgancarre commented
:+1:

2024-12-27 04:33 UTC, adriens requested changes
le DockerFile n'est pas bon du tout : 

```
EXPOSE 8080

#lance le projet
CMD ["mvn", "quarkus:dev"]
```

On doit mettre le jar, pas compiler, d'ailleurs il ne dot pas y avoir de maven dans l'image.

👉 Il faut faire cela avec `jib`: https://quarkus.io/guides/container-image

2024-12-30 21:25 UTC, adriens requested changes
# Dockerfile

Il faut pointer l'unique fichier nécessaire et utiliser jib pour builder l'image et non pas
tout copier puis ignirer avec .dockerignore

```
!pom.xml
!src/
!target/*-runner
!target/*-runner.jar
!target/lib/*
```

... et privilégier le build avec `mvn` qui sait déja quelles ressources embarquer dans l'image.


# README

Simplifier et simplement mentionner que `podman`, `maven` sont des prérequis pour lancer l'application.

2024-12-30 21:46 UTC, morgancarre commented
Je ne sais pas si j'ai bien compris . 
Avec Jib, pas besoin de Dockerfile, il fait tout tout seul ? 
Ici je peux juste enlever le .dockerignore et mettre à jour les commandes pour build et lancer l'image ?

2024-12-30 21:58 UTC, adriens commented
Yep, c'est ça :sloth:

2024-12-30 21:59 UTC, adriens commented
teste et tu verras : 

1. purge ta registry de ton image locale
2. Build avec jib
3. Liste des images et vois la réapparaitre
4. :+1:

2024-12-30 22:14 UTC, morgancarre commented
ça marche bien :+1:

2024-12-30 22:16 UTC, adriens commented
> ça marche bien 👍

Oui, cela sappelle la devex (Developer Experience) : ie. quand tu peux produire plus avec moins d'efforts, c'est très important :+1: ... et tu pourrais en parler dans ton rapport :bulb:

2024-12-30 22:49 UTC, morgancarre commented
Oui, je vais avancer sur mon rapport et le mentionner :100:

2024-12-30 23:14 UTC, merged